name: 'Helm Artifactory Publisher'
description: GitHub Action for packaging, testing helm charts and publishing to Artifactory helm repo'
branding:
  icon: 'archive'
  color: 'blue'
inputs:
  action:
    description: "Type of action to perform [check, dependency, lint, package, check_push, push]"
    required: true
  skip_reindex:
    description: "Skip reindexing of the helm repo"
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v2
    - run: ${{ github.action_path }}/main.sh
      env:
        ACTION: ${{ inputs.action }}
        SKIP_REINDEX: ${{inputs.skip_reindex}}
      shell: bash
    - run: ${{ github.action_path }}/main.sh
      env:
        ACTION: cleanup
      shell: bash
      if: ${{ always() }}
